version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: cabs
      MYSQL_ROOT_PASSWORD: Passw0rd12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  core-service:
    build:
      context: ./core-service
    container_name: core-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  appointment-service:
    build:
      context: ./appointment-service
    container_name: appointment-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  queue-service:
    build:
      context: ./queue-service
    container_name: queue-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql_data: