server.port=8084

spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:mysql://mysql:3306/cabs?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Passw0rd12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=cabs

cabs.jwt.secret=ODI3ZDg3M2IwNGM1NGQ1ZGI5MTE1YWU2ODEzMGM3NGExMTNiNGZiODRhZTQ4Mzg1NjRhZjUwMDYzODU4Nzc4YWFhZjI3ZGEyYWY1Yjc1ODAyMzE1MzNmNzUwZmUyODliNmZhMTBlNGJmYzExMGY1MTdhNmVmZGJiOTA1OGFiZDk=

logging.level.ROOT=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.cabs=INFO
